# Generated by Django 5.0.7 on 2026-07-26 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flipkart_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mdcomputers_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('primeabgb_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.inventoryitem')),
            ],
        ),
    ]
