from rest_framework import views, status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from django.conf import settings
from apps.inventory.models import InventoryItem
from apps.authentication.models import Store
from apps.sales.models import SaleRecord
from django.db.models import Sum
import google.generativeai as genai
import json
import random

# Initialize Gemini
GEMINI_AVAILABLE = False
if settings.GEMINI_API_KEY and len(settings.GEMINI_API_KEY) > 20:
    try:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        gemini_model = genai.GenerativeModel('gemini-2.0-flash')
        GEMINI_AVAILABLE = True
    except Exception:
        pass

class ChatView(views.APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        messages = request.data.get('messages', [])
        
        if not GEMINI_AVAILABLE:
            return Response({
                "response": "⚠️ **Configuration Needed!**\nPlease add a valid `GEMINI_API_KEY` to your backend `.env` file."
            })

        store = Store.objects.get(user=request.user)
        inventory = InventoryItem.objects.filter(store=store)
        
        # Build context
        total_items = inventory.count()
        total_value = sum(item.selling_price * item.quantity for item in inventory)
        low_stock = [item.name for item in inventory if 0 < item.quantity <= 5]
        
        system_context = f"""
        You are TechStock-AI, an expert inventory advisor for PC hardware retailers.
        Current Store: {store.name}
        Total Products: {total_items}
        Total Value: ₹{total_value}
        Low Stock Items: {', '.join(low_stock) if low_stock else 'None'}
        """

        try:
            chat = gemini_model.start_chat(history=[])
            prompt = f"System Context: {system_context}\n\nUser: {messages[-1]['content']}"
            response = chat.send_message(prompt)
            
            return Response({
                "response": response.text
            })
        except Exception as e:
            return Response({"response": f"AI Error: {str(e)}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

class BuildGeneratorView(views.APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        # Stub for PC build generator returning dummy builds
        budget = request.data.get('budget', 50000)
        return Response({
            "budget": budget,
            "use_case": request.data.get('use_case', 'gaming'),
            "builds": [{
                "name": "Budget Gaming Build",
                "total_price": budget,
                "notes": "Generated by AI",
                "components": []
            }]
        })

class DashboardView(views.APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        store = Store.objects.get(user=request.user)
        inventory = InventoryItem.objects.filter(store=store)
        
        total_value = sum(item.selling_price * item.quantity for item in inventory)
        low_stock = inventory.filter(quantity__gt=0, quantity__lte=5).count()
        out_of_stock = inventory.filter(quantity=0).count()
        
        # Mock analytics for phase 2
        return Response({
            "stats": {
                "total_inventory_value": total_value,
                "total_items": inventory.count(),
                "monthly_revenue": 150000,
                "monthly_profit": 25000,
                "avg_margin": 18.5,
                "dead_stock_count": 0,
                "low_stock_count": low_stock,
                "out_of_stock_count": out_of_stock
            },
            "ai_insight": None,
            "recommendations": [],
            "alerts": [],
            "recent_sales": [],
            "category_distribution": []
        })

class ChatStatusView(views.APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        if GEMINI_AVAILABLE:
            return Response({
                "available": True,
                "model": "gemini-2.0-flash",
                "message": "AI services are fully operational."
            })
        return Response({
            "available": False,
            "model": None,
            "message": "Missing API Key"
        })
