from rest_framework import views, status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from django.conf import settings
from apps.inventory.models import InventoryItem
from apps.authentication.models import Store
from apps.sales.models import SaleRecord
from django.db.models import Sum
import google.generativeai as genai
import json
import random

# Initialize Gemini
GEMINI_AVAILABLE = False
if settings.GEMINI_API_KEY and len(settings.GEMINI_API_KEY) > 20:
    try:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        gemini_model = genai.GenerativeModel('gemini-2.0-flash')
        GEMINI_AVAILABLE = True
    except Exception:
        pass

class ChatView(views.APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        messages = request.data.get('messages', [])
        
        if not GEMINI_AVAILABLE:
            return Response({
                "response": "⚠️ **Configuration Needed!**\nPlease add a valid `GEMINI_API_KEY` to your backend `.env` file."
            })

        store = Store.objects.get(user=request.user)
        inventory = InventoryItem.objects.filter(store=store)
        
        # Build context
        total_items = inventory.count()
        total_value = sum(item.selling_price * item.quantity for item in inventory)
        low_stock = [item.name for item in inventory if 0 < item.quantity <= 5]
        
        system_context = f"""
        You are TechStock-AI, an expert inventory advisor for PC hardware retailers.
        Current Store: {store.name}
        Total Products: {total_items}
        Total Value: ₹{total_value}
        Low Stock Items: {', '.join(low_stock) if low_stock else 'None'}
        """

        try:
            chat = gemini_model.start_chat(history=[])
            prompt = f"System Context: {system_context}\n\nUser: {messages[-1]['content']}"
            response = chat.send_message(prompt)
            
            return Response({
                "response": response.text
            })
        except Exception as e:
            return Response({"response": f"AI Error: {str(e)}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

class BuildGeneratorView(views.APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        # Stub for PC build generator returning dummy builds
        budget = request.data.get('budget', 50000)
        return Response({
            "budget": budget,
            "use_case": request.data.get('use_case', 'gaming'),
            "builds": [{
                "name": "Budget Gaming Build",
                "total_price": budget,
                "notes": "Generated by AI",
                "components": []
            }]
        })

class DashboardView(views.APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        store = Store.objects.get(user=request.user)
        inventory = InventoryItem.objects.filter(store=store)
        
        total_value = sum(item.selling_price * item.quantity for item in inventory)
        low_stock = inventory.filter(quantity__gt=0, quantity__lte=5).count()
        out_of_stock = inventory.filter(quantity=0).count()
        
        # Mock analytics for phase 2
        return Response({
            "stats": {
                "total_inventory_value": total_value,
                "total_items": inventory.count(),
                "monthly_revenue": 150000,
                "monthly_profit": 25000,
                "avg_margin": 18.5,
                "dead_stock_count": 0,
                "low_stock_count": low_stock,
                "out_of_stock_count": out_of_stock
            },
            "ai_insight": None,
            "recommendations": [],
            "alerts": [],
            "recent_sales": [],
            "category_distribution": []
        })

class ChatStatusView(views.APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        if GEMINI_AVAILABLE:
            return Response({
                "available": True,
                "model": "gemini-2.0-flash",
                "message": "AI services are fully operational."
            })
        return Response({
            "available": False,
            "model": None,
            "message": "Missing API Key"
        })

class AnalyticsView(views.APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        store = Store.objects.get(user=request.user)
        sales = SaleRecord.objects.filter(store=store)
        
        # Aggregate monthly revenue
        monthly_data = {}
        category_data = {}
        seller_data = {}
        profit_trend = []
        
        for sale in sales:
            month = sale.sold_at.strftime('%Y-%m')
            if month not in monthly_data:
                monthly_data[month] = {"month": month, "revenue": 0, "profit": 0}
            monthly_data[month]["revenue"] += float(sale.sold_price * sale.quantity)
            monthly_data[month]["profit"] += float(sale.profit)
            
            cat = sale.category
            if cat not in category_data:
                category_data[cat] = {"category": cat, "revenue": 0, "profit": 0, "count": 0}
            category_data[cat]["revenue"] += float(sale.sold_price * sale.quantity)
            category_data[cat]["profit"] += float(sale.profit)
            category_data[cat]["count"] += sale.quantity
            
            name = sale.product_name
            if name not in seller_data:
                seller_data[name] = {"name": name, "total_sold": 0, "revenue": 0, "margin": 0}
            seller_data[name]["total_sold"] += sale.quantity
            seller_data[name]["revenue"] += float(sale.sold_price * sale.quantity)
        
        return Response({
            "monthly_revenue": list(monthly_data.values()),
            "category_breakdown": list(category_data.values()),
            "top_sellers": sorted(seller_data.values(), key=lambda x: x["total_sold"], reverse=True)[:10],
            "profit_trend": profit_trend
        })

class RecommendationsView(views.APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        store = Store.objects.get(user=request.user)
        inventory = InventoryItem.objects.filter(store=store)
        
        recommendations = []
        
        # Dead stock recommendations
        dead_stock = inventory.filter(quantity__gt=0, last_sold_days__gte=90)
        for item in dead_stock[:5]:
            recommendations.append({
                "id": str(item.id),
                "type": "dead_stock",
                "product_name": item.name,
                "message": f"{item.name} hasn't sold in {item.last_sold_days} days. Consider a clearance sale.",
                "priority": "high",
                "opportunity_score": 85
            })
        
        # Low stock recommendations
        low_stock = inventory.filter(quantity__gt=0, quantity__lte=5)
        for item in low_stock[:5]:
            recommendations.append({
                "id": str(item.id),
                "type": "restock",
                "product_name": item.name,
                "message": f"{item.name} is running low with only {item.quantity} units left.",
                "priority": "medium",
                "opportunity_score": 60
            })
        
        return Response(recommendations)

class AlertsView(views.APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        store = Store.objects.get(user=request.user)
        inventory = InventoryItem.objects.filter(store=store)
        
        alerts = []
        
        # Out of stock alerts
        out_of_stock = inventory.filter(quantity=0)
        for item in out_of_stock[:5]:
            alerts.append({
                "id": str(item.id),
                "type": "out_of_stock",
                "product_name": item.name,
                "message": f"{item.name} is out of stock!",
                "severity": "critical",
                "created_at": item.updated_at.isoformat()
            })
        
        # Low stock alerts
        low_stock = inventory.filter(quantity__gt=0, quantity__lte=5)
        for item in low_stock[:5]:
            alerts.append({
                "id": str(item.id),
                "type": "low_stock",
                "product_name": item.name,
                "message": f"{item.name} has low stock ({item.quantity} units).",
                "severity": "warning",
                "created_at": item.updated_at.isoformat()
            })
        
        return Response(alerts)
